import defaultTheme from 'tailwindcss/defaultTheme';

export default {
  darkMode: 'class',
  content: ['./src/**/*.{astro,html,js,jsx,ts,tsx}'],
  theme: {
    screens: {
      xs: '375px',
      sm: '640px',
      md: '768px',
      lg: '1024px',
      xl: '1280px',
      '2xl': '1536px',
      '4xl': '2560px',
    },
    extend: {
      fontFamily: {
        sans: ['Linear Display', 'SF Pro Display', 'system-ui', '-apple-system', ...defaultTheme.fontFamily.sans],
        mono: ['Linear Mono', 'GeistMono', ...defaultTheme.fontFamily.mono],
      },
      colors: {
        // Linear Design System - Light Mode (default)
        primary: 'rgb(var(--color-primary) / <alpha-value>)',
        'primary-hover': 'rgb(var(--color-primary-hover) / <alpha-value>)',
        'primary-focus': 'rgb(var(--color-primary-focus) / <alpha-value>)',
        canvas: 'rgb(var(--color-canvas) / <alpha-value>)',
        'surface-1': 'rgb(var(--color-surface-1) / <alpha-value>)',
        'surface-2': 'rgb(var(--color-surface-2) / <alpha-value>)',
        'surface-3': 'rgb(var(--color-surface-3) / <alpha-value>)',
        'surface-4': 'rgb(var(--color-surface-4) / <alpha-value>)',
        ink: 'rgb(var(--color-ink) / <alpha-value>)',
        'ink-muted': 'rgb(var(--color-ink-muted) / <alpha-value>)',
        'ink-subtle': 'rgb(var(--color-ink-subtle) / <alpha-value>)',
        'ink-tertiary': 'rgb(var(--color-ink-tertiary) / <alpha-value>)',
        hairline: 'rgb(var(--color-hairline) / <alpha-value>)',
        'hairline-strong': 'rgb(var(--color-hairline-strong) / <alpha-value>)',
        'hairline-tertiary': 'rgb(var(--color-hairline-tertiary) / <alpha-value>)',
        'inverse-canvas': 'rgb(var(--color-inverse-canvas) / <alpha-value>)',
        'inverse-surface-1': 'rgb(var(--color-inverse-surface-1) / <alpha-value>)',
        'inverse-surface-2': 'rgb(var(--color-inverse-surface-2) / <alpha-value>)',
        'semantic-success': 'rgb(var(--color-semantic-success) / <alpha-value>)',
        'brand-secure': 'rgb(var(--color-brand-secure) / <alpha-value>)',
        'semantic-overlay': 'rgb(var(--color-semantic-overlay) / <alpha-value>)',
      },
      fontSize: {
        'display-xl': ['80px', { lineHeight: '1.05', letterSpacing: '-3.0px' }],
        'display-lg': ['56px', { lineHeight: '1.10', letterSpacing: '-1.8px' }],
        'display-md': ['40px', { lineHeight: '1.15', letterSpacing: '-1.0px' }],
        'headline': ['28px', { lineHeight: '1.20', letterSpacing: '-0.6px' }],
        'card-title': ['22px', { lineHeight: '1.25', letterSpacing: '-0.4px' }],
        'subhead': ['20px', { lineHeight: '1.40', letterSpacing: '-0.2px' }],
        'body-lg': ['18px', { lineHeight: '1.50', letterSpacing: '-0.1px' }],
        'body': ['16px', { lineHeight: '1.50', letterSpacing: '-0.05px' }],
        'body-sm': ['14px', { lineHeight: '1.50', letterSpacing: '0' }],
        'caption': ['12px', { lineHeight: '1.40', letterSpacing: '0' }],
        'button': ['14px', { lineHeight: '1.20', letterSpacing: '0' }],
        'eyebrow': ['13px', { lineHeight: '1.30', letterSpacing: '0.4px' }],
        // Legacy sizes
        xs: ['0.75rem', { lineHeight: '1rem' }],
        sm: ['0.875rem', { lineHeight: '1.25rem' }],
        base: ['1rem', { lineHeight: '1.5rem' }],
        lg: ['1.125rem', { lineHeight: '1.75rem' }],
        xl: ['1.25rem', { lineHeight: '1.75rem' }],
        '2xl': ['1.5rem', { lineHeight: '2rem' }],
        '3xl': ['1.875rem', { lineHeight: '2.25rem' }],
        '4xl': ['2.25rem', { lineHeight: '2.5rem' }],
        '5xl': ['3rem', { lineHeight: '1.2' }],
        '6xl': ['3.75rem', { lineHeight: '1' }],
      },
      borderRadius: {
        xs: '4px',
        sm: '6px',
        md: '8px',
        lg: '12px',
        xl: '16px',
        xxl: '24px',
        pill: '9999px',
      },
      maxWidth: {
        '8xl': '88rem',
        '9xl': '96rem',
      },
      spacing: {
        xxs: '4px',
        xs: '8px',
        sm: '12px',
        md: '16px',
        lg: '24px',
        xl: '32px',
        xxl: '48px',
        section: '96px',
      },
      letterSpacing: {
        'xl-negative': '-3.0px',
        'lg-negative': '-1.8px',
        'md-negative': '-1.0px',
        'sm-negative': '-0.6px',
        'xs-negative': '-0.4px',
        'tight': '-0.2px',
        'tighter': '-0.1px',
        'tightest': '-0.05px',
        'normal': '0',
        'eyebrow': '0.4px',
      },
    },
  },
  plugins: [],
};
